---
prefix: btrfs-nfs-csi
server_name: "{{ prefix }}-agent"
server_type: cx23
server_image: debian-13
# server_location: fsn1
volume_name: "{{ prefix }}-data"
volume_size: 20
agent_base_path: /export/data
agent_listen_addr: ":8080"
agent_version: "0.9.6"
